# CMake generated Testfile for 
# Source directory: /home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/examples/energy
# Build directory: /home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/cmake-cache/examples/energy
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-energy-model-example "ns3.42-energy-model-example-default")
set_tests_properties(ctest-energy-model-example PROPERTIES  WORKING_DIRECTORY "/home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/build/examples/energy/" _BACKTRACE_TRIPLES "/home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/examples/energy/CMakeLists.txt;1;build_example;/home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/examples/energy/CMakeLists.txt;0;")
add_test(ctest-energy-model-with-harvesting-example "ns3.42-energy-model-with-harvesting-example-default")
set_tests_properties(ctest-energy-model-with-harvesting-example PROPERTIES  WORKING_DIRECTORY "/home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/build/examples/energy/" _BACKTRACE_TRIPLES "/home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/examples/energy/CMakeLists.txt;13;build_example;/home/bradas/Documentos/NS3/ns-allinone-3.42/ns-3.42/examples/energy/CMakeLists.txt;0;")
